### ISSUE TITLE
Yamster for Linux possible?

### ISSUE THREAD

**Issue by OldSpeedy** [pgonzal/yamster#2]
Could you provide a Linux version of yamster? Prefereably as an rpm package.
Thanks in advance.

**Comment by octogonz** [comment]
@OldSpeedy as I recall, Linux and Mac don't provide a web browser control that can be easily used by a .NET application.  This makes it difficult to implement the Yammer login window (which supports single-sign on).

For the Mac build, I had handled this with a workaround where you first login using Yamster on Windows, and then you copy the config file (containing the session token) to your Mac.  The token stays valid for a month or more, so although procedure is annoying, you don't have to do it often.

Are you okay with that limitation?  If so, I can see if the code builds on Linux.

**Comment by octogonz** [comment]
Wow -- I can't believe it, but this old code still compiles and runs on Linux!  It took an hour or so of fiddling to find the right library packages/versions.  But the app loads up, and the basic features seem to work (although I can't figure out what Ubuntu did with the main menu):

![Linux](https://user-images.githubusercontent.com/4673363/55017340-bf5d2580-4fad-11e9-911c-d7371550df2d.png)

I'll have to think about a way for people to install this without building from the source code, though.  The SQLite binaries are CPU-specific.  And I probably don't have time to maintain a proper RPM package.

**Comment by OldSpeedy** [comment]
Hello Pete,

 

I'm totally fine with this limitation! It's not a real issue for me, as long as I can have the yammer data inside my linux. :-)

 

Thanks a lot for your work!

 

Olaf

**Comment by octogonz** [comment]
@OldSpeedy What is your Linux distro and version?

**Comment by OldSpeedy** [comment]
Mine is Fedora 28.

**Comment by octogonz** [comment]
Cool, I'll see if I have some time this weekend.

**Comment by OldSpeedy** [comment]
Thanks a lot in advance!!!

Olaf

**Comment by octogonz** [comment]
@OldSpeedy here you go:

1. (On Linux PC) Follow the instructions [here](https://www.monodevelop.com/download/#fndtn-download-lin-centos) to install MonoDevelop for **CentOS 7**, finishing after the step that says `yum install monodevelop`.  
   
   (Note: You don't really need to install the full developer kit.  I just didn't have time to figure out the minimal subset of RPM packages for the Mono runtime.)

2. (On Linux PC) Go to the ["Releases" tab](https://github.com/octogonz/yamster/releases/tag/2.9.3) and download **yamster-2.9.3-fedora-28.tar.gz**

3. (On Linux PC) Extract the tarball somewhere, let's say `~/yamster`.

4. (On Linux PC) To launch the application, run `mono ~/yamster/Yamster.exe`.   For batch operations, use `mono ~/yamster/YamsterCmd.exe`

    **As mentioned above, you need a Windows PC to help you authenticate:**

5.   (On Windows PC) Launch Yamster at least once on Windows, then close the application.  This creates a file `Documents/Yamster/Settings.xml`. Use a text editor to open this file, and change `ProtectTokenWhenSaving` to be `"false"`.  Then save the file.

6.  (On Windows PC) Run Yamster again on Windows, click the "Yammer Sync", and start syncing to ensure you're authenticated.  Close the application.

7. (On Windows PC) Reopen `Documents/Yamster/Settings.xml` and confirm that you now see `(Unprotected)` next to the token.

8. Copy `Settings.xml` from the Windows PC to your Linux PC, and place it under `~/Documents/Yamster/Settings.xml`.  Note that Linux is case sensitive.

(On Linux PC) Now when you launch Yamster on Linux, it should be able to authenticate successfully.

Let me know how it works.  :-)

**Comment by OldSpeedy** [comment]
Hi Pete,

 

I setup everything as you wrote. The version on Windows runs fine and starts to synchronize. The token was saved in Settings.xml.

Unfortunately, I can't get Yamster.exe to ru on Linux. On first run it told me that gtk# libs are not installed. I downloaded it (like for Windows) and tried to install it under wine, but it failed:


$ wine64 uninstaller
0034:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
003e:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"msi83bb.tmp" cannot be loaded
003e:err:module:LdrInitializeThunk Importing dlls for L"C:\\users\\ospeder\\Temp\\msi83bb.tmp" failed, status c0000135
0034:err:msi:execute_script Execution of script 0 halted; action L"setup_pixbuf_loaders.2EE2AF11_DC29_11DC_B7B3_005056C00008" returned 1627
0034:err:msi:ITERATE_Actions Execution halted, action L"InstallFinalize" returned 1627
0034:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0034:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0034:err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1627

 

Mscoree.dll is installed and set to (native/builtin).

 

Any specific wine settings needed for Yamster?

 

Thanks in advance and for your effort!

Olaf


 

Gesendet: Montag, 01. April 2019 um 02:55 Uhr
Von: "Pete Gonzalez" <notifications@github.com>
An: octogonz/yamster <yamster@noreply.github.com>
Cc: OldSpeedy <old_speedy@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [octogonz/yamster] Yamster for Linux possible? (#2)


@OldSpeedy here you go:


	
	Follow the instructions here to install MonoDevelop for CentOS 7, finishing after the step that says yum install monodevelop.

	(Note: You don't really need to install the full developer kit. I just didn't have time to figure out the minimal subset of RPM packages for the Mono runtime.)
	
	
	Go to the "Releases" tab and download yamster-2.9.3-fedora-28.tar.gz
	
	
	Extract the tarball somewhere, let's say ~/yamster.
	
	
	To launch the application, run mono ~/yamster/Yamster.exe. For batch operations, use mono ~/yamster/YamsterCmd.exe

	As mentioned above, you need a Windows PC to help you authenticate:
	
	
	After running Yamster at least once on Windows, and close the application. This creates a file Documents/Yamster/Settings.xml. Use a text editor to open this file, and change ProtectTokenWhenSaving to be "false". Then save the file.
	
	
	Run Yamster again on Windows, click the "Yammer Sync", and start syncing to ensure you're authenticated. Close the application.
	
	
	Reopen Documents/Yamster/Settings.xml and confirm that you now see (Unprotected) next to the token.
	
	
	Copy Settings.xml to your Linux box, and place it under ~/Documents/Yamster/Settings.xml. Note that Linux is case sensitive.
	


Now when you launch Yamster on Linux, it should be able to authenticate successfully.

Let me know how it works. :-)

**Comment by octogonz** [comment]
@OldSpeedy don't use Wine.  That is for emulating Windows.  Even though the Yamster file extension is ".exe", this is NOT a Windows executable.  It is a Linux binary that can be run using the Mono system (`mono ~/yamster/Yamster.exe` as I described above).

Mono and the Linux version of gtk# should get installed as part of this step:

> 1. Follow the instructions [here](https://www.monodevelop.com/download/#fndtn-download-lin-centos) to install MonoDevelop for **CentOS 7**, finishing after the step that says `yum install monodevelop`.  

My instructions say to install MonoDevelop for >>CentOS<< which is a Linux distribution.  It will work on Fedora.

**Comment by octogonz** [comment]
I updated the instructions to clarify which steps are Windows/Linux

**Comment by OldSpeedy** [comment]
Hello,

I did not use wine explicitly, it was used implicitly! I will check whether a gnome file suffix association starts wine implicitly.
Olaf
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 07.04.19, 20:38, Pete Gonzalez <notifications@github.com> schrieb:
@OldSpeedy don't use Wine.  That is for emulating Windows.  Even though the Yamster file extension is ".exe", this is NOT a Windows executable.  It is a Linux binary that can be run using the Mono system (mono ~/yamster/Yamster.exe as I described above).
Mono and the Linux version of gtk# should get installed as part of this step:


Follow the instructions here to install MonoDevelop for CentOS 7, finishing after the step that says yum install monodevelop.


My instructions say to install MonoDevelop for >>CentOS<< which is a Linux distribution.  It will work on Fedora.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/octogonz/yamster","title":"octogonz/yamster","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/octogonz/yamster"}},"updates":{"snippets":[{"icon":"PERSON","message":"@octogonz in #2: @OldSpeedy don't use Wine.  That is for emulating Windows.  Even though the Yamster file extension is \".exe\", this is NOT a Windows executable.  It is a Linux binary that can be run using the Mono system (`mono ~/yamster/Yamster.exe` as I described above).\r\n\r\nMono and the Linux version of gtk# should get installed as part of this step:\r\n\r\n\u003e 1. Follow the instructions [here](https://www.monodevelop.com/download/#fndtn-download-lin-centos) to install MonoDevelop for **CentOS 7**, finishing after the step that says `yum install monodevelop`.  \r\n\r\nMy instructions say to install MonoDevelop for \u003e\u003eCentOS\u003c\u003c which is a Linux distribution.  It will work on Fedora."}],"action":{"name":"View Issue","url":"https://github.com/octogonz/yamster/issues/2#issuecomment-480617842"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/octogonz/yamster/issues/2#issuecomment-480617842",
"url": "https://github.com/octogonz/yamster/issues/2#issuecomment-480617842",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by OldSpeedy** [comment]
Hello Pete,

 

the point, I missed, was the "mono" in front of the executable to execute Yamster in the mono context.

So, it is running, but it does not go online. When I try to add an additional group I receive the following error: SSL error:1000007d:SSL CERTIFICATE_VERIFY_FAILED.

See attached screen shot for reference.

Thanks a lot so far!

Olaf

 

 

Gesendet: Sonntag, 07. April 2019 um 20:38 Uhr
Von: "Pete Gonzalez" <notifications@github.com>
An: octogonz/yamster <yamster@noreply.github.com>
Cc: OldSpeedy <old_speedy@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [octogonz/yamster] Yamster for Linux possible? (#2)


@OldSpeedy don't use Wine. That is for emulating Windows. Even though the Yamster file extension is ".exe", this is NOT a Windows executable. It is a Linux binary that can be run using the Mono system (mono ~/yamster/Yamster.exe as I described above).

Mono and the Linux version of gtk# should get installed as part of this step:



	Follow the instructions here to install MonoDevelop for CentOS 7, finishing after the step that says yum install monodevelop.



My instructions say to install MonoDevelop for >>CentOS<< which is a Linux distribution. It will work on Fedora.

**Comment by OldSpeedy** [comment]
Hello Pete,

 

sorry, I shouldn't send the answer too early! I found out how to fix the SSL error while searching the web:


# cd /etc/ssl/certs/
# cert-sync ca-bundle.crt

Now Yamster starts and I can sync my desired groups!!

 

Thanks a lot for your extraordinary work!

old_speedy

 



Gesendet: Sonntag, 07. April 2019 um 20:38 Uhr
Von: "Pete Gonzalez" <notifications@github.com>
An: octogonz/yamster <yamster@noreply.github.com>
Cc: OldSpeedy <old_speedy@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [octogonz/yamster] Yamster for Linux possible? (#2)


@OldSpeedy don't use Wine. That is for emulating Windows. Even though the Yamster file extension is ".exe", this is NOT a Windows executable. It is a Linux binary that can be run using the Mono system (mono ~/yamster/Yamster.exe as I described above).

Mono and the Linux version of gtk# should get installed as part of this step:



	Follow the instructions here to install MonoDevelop for CentOS 7, finishing after the step that says yum install monodevelop.



My instructions say to install MonoDevelop for >>CentOS<< which is a Linux distribution. It will work on Fedora.

**Comment by octogonz** [comment]
Glad you got it working. Have fun yammering!
