### ISSUE TITLE
Yamster Sync errors out with error 500

### ISSUE THREAD

**Issue by ArnoutVerbeken** [pgonzal/yamster#3]
Hello,

Recently, more and more when I do a Sync it just fails with the error specified further in this mail.
When it does start the sync, it only runs for a couple of minutes/half an hour before it gives me the same error.
I don't know why this is happening, hoping you can help with some debug tracing....

Thanks in advance.

The error I got is a popup with the following message:

> An error occurred:
>   --> The remote server returned an error: (500) Internal Server Error.
>   --> Error: <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="utf-8" />
>     <meta http-equiv="X-UA-Compatible" content="IE=edge" />
> 
>     <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
>     <title>Something went wrong (500)</title>
> 
>     <style>
>       body {
>         margin: 0;
>         background: #f3f5f8;
>         color: #495361;
>         font-family: Helvetica, Arial, sans-serif;
>         text-align: center;
>         font-size: 16px;
>         line-height: 20px;
>       }
>       a {
>         color: #386cbb;
>       }
>       .logo {
>         position: absolute;
>         margin: 35px 50px;
>         opacity: 0.95;
>         left: 0;
>         top: 0;
>       }
>       h1 {
>         margin: 14px 0;
>         font-size: 24px;
>         line-height: 32px;
>       }
>       p {
>         margin: 8px 0;
>         color: #646d7a;
>       }
>       .errorbox {
>         position: absolute;
>         margin: auto;
>         top: 0;
>         right: 0;
>         bottom: 0;
>         left: 0;
>         width: 500px;
>         height: 480px;
>       }
>       @media (max-height: 600px) {
>         .errorbox {
>           position: static;
>           display: block;
>           margin: 48px auto;
>         }
>       }
>       @media (max-width: 800px) {
>         .logo {
>           margin: 20px 25px;
>           opacity: 0.95;
>           left: 0;
>           top: 0;
>         }
>         .errorbox {
>           position: static;
>           display: block;
>           margin: 52px auto;
>           width: 80%;
>         }
>         .errorbox svg {
>           width: 90%;
>           height: 90%;
>         }
>       }
>     </style>
>   </head>
> 
>   <body>
>     <div id="logo" class="logo">
>       <a href="/" aria-label="Yammer">
>         <svg width="42" height="42" xmlns="http://www.w3.org/2000/svg">
>           <path
>             d="M36.98 26.629l-3.5-.908-9.104-2.373v-5.015l8.28-2.143.309-.08 2.734-.709 1.28-.333c.829 3.809.829 7.75 0 11.56zm-5.81 3.624a24.01 24.01 0 0 1-4.161 6.585l-5.684-5.663h1.326c.95 0 1.725-.774 1.725-1.722v-4.578L32.3 26.94a26.646 26.646 0 0 1-1.129 3.315v-.003zM26.986 4.854a24.076 24.076 0 0 1 5.243 9.775l.039.135-7.892 2.047v-4.574c0-.947-.777-1.722-1.725-1.722h-1.339l5.676-5.66h-.002zm-7.62 11.421l-3.638 6.313a.784.784 0 0 0-.103.391v3.194a1.524 1.524 0 0 1-1.524 1.521h-.235c-.841.001-1.524-.68-1.527-1.52v-3.158a.798.798 0 0 0-.096-.381l-3.568-6.376a1.505 1.505 0 0 1 .016-1.513 1.51 1.51 0 0 1 1.316-.75h.226c.573 0 1.09.316 1.356.824l2.514 4.86 2.594-4.876a1.52 1.52 0 0 1 1.345-.808c.552 0 1.046.283 1.321.76a1.5 1.5 0 0 1 0 1.519h.002zm18.929-2.097c-.1-.418-.483-.698-.95-.698l-2.015.505-.003-.014-1.542.4-.086.023-.042-.15a25.52 25.52 0 0 0-5.951-10.798.975.975 0 0 0-1.368-.032l-7.115 7.105H5.4a1.722 1.722 0 0 0-1.725 1.718v17.216c0 .948.774 1.722 1.723 1.722h13.834l7.128 7.103a.945.945 0 0 0 1.362-.027 25.449 25.449 0 0 0 4.811-7.425 27.904 27.904 0 0 0 1.196-3.513v-.002l1.411.369.002-.005 2.044.53.188.023a.933.933 0 0 0 .917-.703c.523-2.17.787-4.417.787-6.68a28.596 28.596 0 0 0-.783-6.667z"
>             fill-rule="nonzero"
>             fill="#386CBB"
>           />
>         </svg>
>       </a>
>     </div>
> 
>     <section class="errorbox">
>       <div class="errorbox-content">
>         <figure aria-hidden="true">
>           <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 270 270"><defs><path id="a" d="M90.7 47.6V11.5c0-3.4-2.9-6.3-6.3-6.3s-6.3 2.7-6.3 6.3v36.1H51.4V11.5c0-3.4-2.9-6.3-6.3-6.3s-6.3 2.9-6.3 6.3v36.1h-15v34.5c0 16.6 9.7 30.9 23.8 37.4h-1.4v15.7c0 10.3 8.2 18.8 18.6 18.8 10.2 0 18.6-8.3 18.6-18.8v-15.7H82c14-6.5 23.8-20.8 23.8-37.4V47.6H90.7z"/></defs><clipPath id="b"><use xlink:href="#a" overflow="visible"/></clipPath><g clip-path="url(#b)"><defs><path id="c" d="M21.9 3.3h226.2v307H21.9z"/></defs><clipPath id="d"><use xlink:href="#c" overflow="visible"/></clipPath><path clip-path="url(#d)" fill="#FFF" d="M14.8-3.9h100.1V163H14.8z"/></g><defs><path id="e" d="M97 48.1V15.6c0-3.6-2.9-6.5-6.3-6.5s-6.3 2.9-6.3 6.3v36.1H57.7V15.4c0-3.4-2.9-6.3-6.3-6.3s-6.3 2.9-6.3 6.3v36.1h-15V86c0 16.6 9.7 30.9 23.8 37.4h-1.4v15.7c0 10.3 8.2 18.8 18.6 18.8 10.2 0 18.6-8.3 18.6-18.8v-15.7c14-6.5 22.4-20.8 22.4-37.4V51.7L97 48.1z"/></defs><clipPath id="f"><use xlink:href="#e" overflow="visible"/></clipPath><g clip-path="url(#f)"><defs><path id="g" d="M21.9 3.3h226.2v307H21.9z"/></defs><clipPath id="h"><use xlink:href="#g" overflow="visible"/></clipPath><path clip-path="url(#h)" fill="#DDE0E6" d="M21.1.1h100.1V167H21.1z"/></g><defs><path id="i" d="M64.5 125.2c-23.6 0-42.6-19.2-42.6-43V47.6c0-1 .8-1.8 1.8-1.8h81.9c1 0 1.8.8 1.8 1.8v34.5c-.2 23.9-19.3 43.1-42.9 43.1zm-39-75.8v32.9c0 21.8 17.5 39.4 39.1 39.4s39.1-17.6 39.2-39.5V49.4H25.5z"/></defs><clipPath id="j"><use xlink:href="#i" overflow="visible"/></clipPath><g clip-path="url(#j)"><defs><path id="k" d="M21.9 3.3h226.2v307H21.9z"/></defs><clipPath id="l"><use xlink:href="#k" overflow="visible"/></clipPath><path clip-path="url(#l)" fill="#386CBA" d="M12.9 36.8h103.5v97.5H12.9z"/></g><path fill="#386CBA" d="M73.1 142.4H55.9c-1 0-1.8-.8-1.8-1.8s.8-1.8 1.8-1.8h17.2c1 0 1.8.8 1.8 1.8s-.8 1.8-1.8 1.8zm0-8.8H55.9c-1 0-1.8-.8-1.8-1.8s.8-1.8 1.8-1.8h17.2c1 0 1.8.8 1.8 1.8s-.8 1.8-1.8 1.8zm17.2-84.2H77.8c-1 0-1.8-.8-1.8-1.8V11.5c0-4.4 3.7-8.1 8.1-8.1s8.1 3.7 8.1 8.1v36.1c-.1 1-.9 1.8-1.9 1.8zm-10.7-3.6h8.9V11.5c0-2.4-2-4.5-4.5-4.5s-4.5 2.1-4.5 4.5v34.3zm-28.3 3.6H38.7c-1 0-1.8-.8-1.8-1.8V11.5c0-4.4 3.7-8.1 8.1-8.1s8.1 3.7 8.1 8.1v36.1c0 1-.8 1.8-1.8 1.8zm-10.8-3.6h8.9V11.5C49.5 9 47.4 7 45 7s-4.5 2.1-4.5 4.5v34.3z"/><g><defs><path id="m" d="M165 189.3h-3.8c-9.4 0-17-7.7-17-17.2v-9.8c0-10.7-8.6-19.3-19.2-19.3s-19.2 8.7-19.2 19.3V211c0 10.9-8.7 19.7-19.5 19.7s-19.5-8.8-19.5-19.7v-55.3c0-1-.8-1.8-1.8-1.8s-1.8.8-1.8 1.8V211c0 12.9 10.3 23.3 23.1 23.3s23.1-10.4 23.1-23.3v-48.6c0-8.6 7-15.7 15.6-15.7s15.6 7 15.6 15.7v9.8c0 11.5 9.2 20.8 20.6 20.8h3.8c1 0 1.8-.8 1.8-1.8 0-1.1-.8-1.9-1.8-1.9zm58.2 1.8c10.8 0 19.5 8.8 19.5 19.7v54c0 1 .8 1.8 1.8 1.8s1.8-.8 1.8-1.8v-54c0-12.9-10.3-23.3-23.1-23.3-1 0-1.8.8-1.8 1.8.1 1 .9 1.8 1.8 1.8zm-29-22.1v12.5c0 1 .8 1.8 1.8 1.8s1.8-.8 1.8-1.8V169c0-1-.8-1.8-1.8-1.8s-1.8.8-1.8 1.8zm0 33.9v12.5c0 1 .8 1.8 1.8 1.8s1.8-.8 1.8-1.8v-12.5c0-1-.8-1.8-1.8-1.8s-1.8.8-1.8 1.8zm-19.1-20.6l10.7 6.1c.9.5 2 .2 2.4-.7.5-.9.2-2-.7-2.5l-10.7-6.1c-.9-.5-2-.2-2.4.7-.5.9-.2 2 .7 2.5zm29.2 16.9l10.7 6.1c.9.5 2 .2 2.4-.7.5-.9.2-2-.7-2.5L206 196c-.9-.5-2-.2-2.4.7s-.2 2.1.7 2.5zm-27.5 6.2l10.7-6.1c.9-.5 1.2-1.6.7-2.5s-1.6-1.2-2.4-.7l-10.7 6.1c-.9.5-1.2 1.6-.7 2.5.5.9 1.6 1.2 2.4.7zm29.2-17l10.7-6.1c.9-.5 1.2-1.6.7-2.5-.5-.9-1.6-1.2-2.4-.7l-10.7 6.1c-.9.5-1.2 1.6-.7 2.5.5.9 1.6 1.2 2.4.7z"/></defs><clipPath id="n"><use xlink:href="#m" overflow="visible"/></clipPath><g clip-path="url(#n)"><defs><path id="o" d="M21.9 310.3l226.2-40V3.3H21.9z"/></defs><clipPath id="p"><use xlink:href="#o" overflow="visible"/></clipPath><path clip-path="url(#p)" fill="#386CBA" d="M54.2 123h201.2v151.6l-201.2 40z"/></g></g><g><defs><path id="q" d="M88.5 106.1c0 3.8-4.5.7-9.9.7s-9.9 3.1-9.9-.7S73.3 96 78.7 96s9.8 6.3 9.8 10.1"/></defs><clipPath id="r"><use xlink:href="#q" overflow="visible"/></clipPath><g clip-path="url(#r)"><defs><path id="s" d="M21.9 3.3h226.2v307H21.9z"/></defs><clipPath id="t"><use xlink:href="#s" overflow="visible"/></clipPath><path clip-path="url(#t)" fill="#FFF" d="M59.8 87h37.8v30.1H59.8z"/></g></g><g><defs><path id="u" d="M86.2 104.1c0 2.1-1.1 3.5-3.1 3.7-1 .1-1 .1-4.3-.6-1.8-.4-3-.5-4.3-.5s-2.5.2-4.3.5c-3.3.7-3.3.7-4.3.6-1.9-.2-3.1-1.5-3.1-3.7 0-5.3 5.7-11.9 11.6-11.9 6.2 0 11.8 6.5 11.8 11.9zm-3.6 0c0-3.5-4.1-8.3-8.1-8.3-3.8 0-8.1 4.9-8.1 8.3v.1c.4 0 .8-.1 3.1-.6 2-.4 3.4-.6 5-.6s3 .2 5 .6c2.3.5 2.7.6 3.1.5 0 .1 0 .1 0 0z"/></defs><clipPath id="v"><use xlink:href="#u" overflow="visible"/></clipPath><g clip-path="url(#v)"><defs><path id="w" d="M21.9 3.3h226.2v307H21.9z"/></defs><clipPath id="x"><use xlink:href="#w" overflow="visible"/></clipPath><path clip-path="url(#x)" fill="#386CBA" d="M53.9 83.2h41.3v33.7H53.9z"/></g></g><g><defs><ellipse id="y" cx="90.9" cy="85.5" rx="2.7" ry="2.7"/></defs><clipPath id="z"><use xlink:href="#y" overflow="visible"/></clipPath><g clip-path="url(#z)"><defs><path id="A" d="M21.9 3.3h226.2v307H21.9z"/></defs><clipPath id="B"><use xlink:href="#A" overflow="visible"/></clipPath><path clip-path="url(#B)" fill="#386CBB" d="M79.1 73.8h23.4v23.5H79.1z"/></g></g><g><defs><ellipse id="C" cx="58.6" cy="85.5" rx="2.7" ry="2.7"/></defs><clipPath id="D"><use xlink:href="#C" overflow="visible"/></clipPath><g clip-path="url(#D)"><defs><path id="E" d="M21.9 3.3h226.2v307H21.9z"/></defs><clipPath id="F"><use xlink:href="#E" overflow="visible"/></clipPath><path clip-path="url(#F)" fill="#386CBB" d="M46.9 73.8h23.4v23.5H46.9z"/></g></g><g><defs><path id="G" d="M80.6 120.7v15.7c0 9.4-7.5 17-16.8 17s-16.8-7.6-16.8-17v-15.7c0-1-.8-1.8-1.8-1.8s-1.8.8-1.8 1.8v15.7c0 11.4 9.2 20.6 20.4 20.6 11.3 0 20.4-9.2 20.4-20.6v-15.7c0-1-.8-1.8-1.8-1.8-.9 0-1.8.8-1.8 1.8z"/></defs><clipPath id="H"><use xlink:href="#G" overflow="visible"/></clipPath><g clip-path="url(#H)"><defs><path id="I" d="M21.9 3.3h226.2v307H21.9z"/></defs><clipPath id="J"><use xlink:href="#I" overflow="visible"/></clipPath><path clip-path="url(#J)" fill="#386CBA" d="M34.4 109.9h58.9v56.2H34.4z"/></g></g></svg>
>         </figure>
>         <h1>
>           This 500 error rarely happens, but even Yammer’s https don’t deliver
>           sometimes.
>         </h1>
>         <p>
>           The team’s working on it. In the meantime,
>           <a href="/">go to Yammer</a>.
>         </p>
>       </div>
>     </section>
>   </body>
> </html>
> 
>   --> A problem occurred while syncing messages.

**Comment by octogonz** [comment]
> ```
> This 500 error rarely happens, but even Yammer’s https don’t deliver sometimes.
> ```

Seems like a problem with the Yammer service, not the Yamster client.
